spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: test
  datasource.url: jdbc:h2:~/test3
  datasource.username: sa
  datasource.password:
